### ISSUE TITLE
tun/tap doesn't build with Xcode 8

### ISSUE THREAD

**Issue by Davidllo** [Tunnelblick/Tunnelblick#336]
Hi,

I'm not a Mac expert, so I'm not sure if this is really an issue...

The Makefiles in tuntap-201**/tuntap/src/[tun/tap] have hard-coded references to /System/Library/Frameworks/Kernel.framework/Headers

resulting in this:

../lock.h:35:10: fatal error: 'kern/locks.h' file not found
# include <kern/locks.h>

On my Mac (at least), these files appear  to be here...

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers

Not sure what the correct location should be on a Mac, but the obvious tweak to the Makefiles fixes this for me, and the project builds to completion...

As you have patch files, you presumably could patch both include locations in to the gcc line...

Regards!

**Comment by jkbullard** [comment]
- Are you using the instructions in the "Building Tunnelblick from Source Code.markdown" document included with the source code?
- What version of OS X are you building on?
- What version of Xcode are you using?

Tunnelblick releases are build on OS X 10.11.6 using Xcode 7.3.1.

**Comment by Davidllo** [comment]
Hi,

OSX 10.11.6.  I am on XCode 8 which is all I can get from the AppStore at this point, I think.

I followed the doc (apart from the "don't use XCode 8" part), and it built successfully.  The only issue was the Kernel framework headers being in a different location on my machine.

Is the crash in openvpn, or the Tunnelblick GUI, by the way?  If it is only an intermittent problem it won't really affect what I am trying to do.

Thanks,

David

**Comment by jkbullard** [comment]
The crashes (so far) have only been in Tunnelblick itself, not in OpenVPN. But there have only been a small number of crashes reported, so there is no guarantee that OpenVPN won't also be affected by whatever the problem is. (Of course, it is also possible that it is an error in the Tunnelblick source code itself that is causing the problem, and Xcode 8 is only exposing it, so OpenVPN might not be affected.)

I'll leave this issue open until Tunnelblick builds properly on Xcode 8.

**Comment by jkbullard** [comment]
The missing "kern/locks.h" problem is caused by newer Xcode installs not including tools that were previously included. I have updated "Building Tunnelblick from Source Code.markdown" to include the following instructions to fix this:

Xcode 7.0+ also need to have the command line tools installed. You can do that in Terminal with the following command: ```xcode-select --install```

However, there is no more info on the problems running Tunnelblick if it is built with Xcode 8. I am closing this issue and will create a new one for that.

**Comment by macvk** [comment]
I have xcode 10.1 and` xcode-select --install `doesn't solve the issue. 
I've changed 4 files 

tuntap-20111101/tuntap/src/tap/Makefile
tuntap-20111101/tuntap/src/tun/Makefile
tuntap-20141104/tuntap/src/tap/Makefile
tuntap-20141104/tuntap/src/tun/Makefile

-INCLUDE = -I.. -I/System/Library/Frameworks/Kernel.framework/Headers
+INCLUDE = -I.. -I$(SDK_DIR)/System/Library/Frameworks/Kernel.framework/Headers -I$(SDK_DIR)

**Comment by jkbullard** [comment]
@macvk - Thanks!
